server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salonbooking
    username: root
    password: Devansh2005@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true