server:
  port: 8082
spring:
  datasource:
    username: root
    password: Devansh2005@#
    url: jdbc:mysql://localhost:3306/salonbooking
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true